#!/usr/bin/env bash
# This script displays information about subdomains for a given domain.

# Function to retrieve and display information about a subdomain
domain_information() {
    # Perform DNS search for the subdomain under the specified domain
    line=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $1, $4}')
    # Extract relevant information and print it
    echo "The subdomain $2 is a $line record and points to $1"
}

# Check the number of arguments passed to the script
if [ "$#" == 1 ]; then
    # If there is only one argument
    # Call the domain information function with predefined subdomain names
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" == 2 ]; then
    # If there are two arguments, call the domain information
    # function with the provided subdomain name
    domain_information "$1" "$2"
fi

