#!/usr/bin/env bash
# This bash script configures Nginx for a custom 404 page

# Start with updating the package lists for available software packages
apt-get update

# Then install Nginx if not already installed
if ! dpkg -l | grep -q nginx; then
    apt-get install -y nginx
fi

# Create a custom 404 HTML page with the specified content
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx to use the custom 404 page
echo "server {
    listen 80;
    server_name lizcode.tech;

    location / {
        root /var/www/html;
        index index.html;
    }

    error_page 404 /404.html;

    location /404.html {
        internal;
    }
}" > /etc/nginx/sites-available/custom_404

# Create a symbolic link to enable the new site configuration
ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Test the Nginx configuration and reload
nginx -t
service nginx reload

