#!/usr/bin/env bash
# Configure an nginx server to listen on port 80
ln -s /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default
# restarting nginx.
service nginx restart
# Terminate the first nginx process ID
kill "$(pgrep 'nginx' | head - 1)"
