#!/usr/bin/env bash
# configuration of nginx fixed to run (to listen to port 80)
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
