#!/usr/bin/env bash
# Pull the Docker image
docker pull holbertonschool/265-0

# Create a Docker container from the image. Map port 8080 to port 80 and run it in detached mode.
container_id=$(docker run -p 8080:80 -d holbertonschool/265-0)

# Check if the Docker container is running
docker ps

# Use `curl` to query the container on port 8080
curl http://localhost:8080

# If an error occurs, debug by accessing the container
# Replace CONTAINER_ID with the actual container ID
docker exec -it $container_id /bin/bash

# Navigate to the Apache document root directory located at `/var/www/html`
# Change directory
cd /var/www/html

# View the content of index.html
cat index.html

# Exit the container shell and rerun `curl` to verify if it's working correctly
exit

# If it's working perfectly, stop the container
docker stop $container_id

